In [56]:
def answer_one():
    
    import numpy as np
    import pandas as pd
    from sklearn.model_selection import train_test_split
    from sklearn.linear_model import LinearRegression
    from sklearn.preprocessing import PolynomialFeatures

    np.random.seed(0)
    n = 15
    x = np.linspace(0,10,n) + np.random.randn(n)/5
    y = np.sin(x)+x/6 + np.random.randn(n)/10
    pred_values = np.linspace(0,10,100).reshape(-1,1)
    ar = np.zeros((4,100))


    X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=0)

    for i,degree in enumerate([1,3,6,9]):
        poly = PolynomialFeatures(degree = degree)
        X_poly = poly.fit_transform (X_train.reshape(-1,1))
        clf = LinearRegression().fit(X_poly, y_train)
        y_poly = clf.predict(poly.fit_transform(pred_values))
        ar[i,:]=y_poly
    return ar

answer_one()


array([[ 2.53040195e-01,  2.69201547e-01,  2.85362899e-01,
         3.01524251e-01,  3.17685603e-01,  3.33846955e-01,
         3.50008306e-01,  3.66169658e-01,  3.82331010e-01,
         3.98492362e-01,  4.14653714e-01,  4.30815066e-01,
         4.46976417e-01,  4.63137769e-01,  4.79299121e-01,
         4.95460473e-01,  5.11621825e-01,  5.27783177e-01,
         5.43944529e-01,  5.60105880e-01,  5.76267232e-01,
         5.92428584e-01,  6.08589936e-01,  6.24751288e-01,
         6.40912640e-01,  6.57073992e-01,  6.73235343e-01,
         6.89396695e-01,  7.05558047e-01,  7.21719399e-01,
         7.37880751e-01,  7.54042103e-01,  7.70203454e-01,
         7.86364806e-01,  8.02526158e-01,  8.18687510e-01,
         8.34848862e-01,  8.51010214e-01,  8.67171566e-01,
         8.83332917e-01,  8.99494269e-01,  9.15655621e-01,
         9.31816973e-01,  9.47978325e-01,  9.64139677e-01,
         9.80301028e-01,  9.96462380e-01,  1.01262373e+00,
         1.02878508e+00,  1.04494644e+00,  1.06110779e+0

In [12]:
def answer_two():
    import numpy as np
    import pandas as pd
    from sklearn.model_selection import train_test_split
    from sklearn.linear_model import LinearRegression
    from sklearn.preprocessing import PolynomialFeatures
    from sklearn.metrics import r2_score


    np.random.seed(0)
    n = 15
    x = np.linspace(0,10,n) + np.random.randn(n)/5
    y = np.sin(x)+x/6 + np.random.randn(n)/10

    X_train, X_test, y_train, y_test = train_test_split(x,y,random_state=0)

    training_score = np.zeros(10)
    test_score = np.zeros(10)

    for i in (np.arange(0,10)):
    
        poly = PolynomialFeatures(degree=i)
        X_poly = poly.fit_transform(X_train.reshape(-1,1))
        clf = LinearRegression().fit(X_poly, y_train)
        training_score[i] = clf.score(X_poly, y_train)
        X_test_poly = poly.fit_transform(X_test.reshape(-1,1))
        test_score[i] = clf.score(X_test_poly, y_test)
    return (training_score, test_score)

answer_two()

(array([0.        , 0.42924578, 0.4510998 , 0.58719954, 0.91941945,
        0.97578641, 0.99018233, 0.99352509, 0.99637545, 0.99803706]),
 array([-0.47808642, -0.45237104, -0.06856984,  0.00533105,  0.73004943,
         0.87708301,  0.9214094 ,  0.92021504,  0.6324795 , -0.64524777]))

In [93]:
def answer_three():
    
    fits = answer_two()
    training_score = fits[0]
    test_score = fits[1]
    fits = pd.Series(training_score, test_score)
    fits = fits.to_frame()
    fits.rename({0:'Training Scores'},axis=1,inplace=True)
    fits.reset_index(inplace=True)
    fits.rename({'index':'Test Scores'},axis=1, inplace=True)
    underfit= fits.index[2]
    overfit = fits.index[8]
    good_generalization = fits.index[6]
    return underfit, overfit,good_generalization

answer_three()

(2, 8, 6)

In [16]:
def answer_four():
    
    import numpy as np
    import pandas as pd
    from sklearn.model_selection import train_test_split
    from sklearn.linear_model import LinearRegression
    from sklearn.preprocessing import PolynomialFeatures
    from sklearn.linear_model import Lasso


    np.random.seed(0)
    n = 15
    x = np.linspace(0,10,n) + np.random.randn(n)/5
    y = np.sin(x)+x/6 + np.random.randn(n)/10
    pred_values = np.linspace(0,10,100).reshape(-1,1)
    


    X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=0)

    poly = PolynomialFeatures (degree = 12)
    X_train_poly = poly.fit_transform(X_train.reshape(-1,1))
    X_test_poly = poly.fit_transform(X_test.reshape(-1,1))
    linreg = LinearRegression().fit(X_train_poly,y_train)
    linlasso = Lasso(alpha=0.01, max_iter=10000).fit(X_train_poly,y_train)
    linreg_score = linreg.score(X_test_poly, y_test)
    linlasso_score = linlasso.score(X_test_poly,y_test)
    return(linreg_score,linlasso_score)

answer_four()

/Users/emilyvincett/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.3556421695889839, tolerance: 0.00068949825403828
  model = cd_fast.enet_coordinate_descent(


(-4.311980555741178, 0.8406625614750356)

In [27]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split


mush_df = pd.read_csv('/Users/emilyvincett/downloads/mushrooms.csv')
mush_df2 = pd.get_dummies(mush_df)

X_mush = mush_df2.iloc[:,2:]
y_mush = mush_df2.iloc[:,1]

# use the variables X_train2, y_train2 for Question 5
X_train2, X_test2, y_train2, y_test2 = train_test_split(X_mush, y_mush, random_state=0)

# For performance reasons in Questions 6 and 7, we will create a smaller version of the
# entire mushroom dataset for use in those questions.  For simplicity we'll just re-use
# the 25% test split created above as the representative subset.
#
# Use the variables X_subset, y_subset for Questions 6 and 7.
X_subset = X_test2
y_subset = y_test2

In [84]:
def answer_five():
    
    import pandas as pd
    import numpy as np
    from sklearn.model_selection import train_test_split
    from sklearn.tree import DecisionTreeClassifier

    clf_tree = DecisionTreeClassifier().fit(X_train2, y_train2)
    features = clf_tree.feature_importances_

    X_train2.columns

    feature_importance = pd.DataFrame(X_train2.columns, features)
    feature_importance = feature_importance.reset_index()
    feature_importance = feature_importance.rename({'index':'Importance',0:'Feature'},axis=1)
    feature_importance = feature_importance.sort_values('Importance',ascending=False)
    x = feature_importance['Feature'].head(5).tolist()
    return print (x, end='')

answer_five()

['odor_n', 'stalk-root_c', 'stalk-root_r', 'spore-print-color_r', 'spore-print-color_u']

In [225]:
def answer_six():
    
    from sklearn.svm import SVC
    from sklearn.model_selection import validation_curve
    import pandas as pd
    import numpy as np
    from sklearn.model_selection import train_test_split


    mush_df = pd.read_csv('/Users/emilyvincett/downloads/mushrooms.csv')
    mush_df2 = pd.get_dummies(mush_df)

    X_mush = mush_df2.iloc[:,2:]
    y_mush = mush_df2.iloc[:,1]

    # use the variables X_train2, y_train2 for Question 5
    X_train2, X_test2, y_train2, y_test2 = train_test_split(X_mush, y_mush, random_state=0)

    # For performance reasons in Questions 6 and 7, we will create a smaller version of the
    # entire mushroom dataset for use in those questions.  For simplicity we'll just re-use
    # the 25% test split created above as the representative subset.
    #
    # Use the variables X_subset, y_subset for Questions 6 and 7.
    X_subset = X_test2
    y_subset = y_test2

    svc = SVC(kernel = 'rbf', C=1, random_state=0)
    param_range = np.logspace(-4,1,6)
    train_scores,test_scores = validation_curve(svc,X_subset,y_subset,
                                            param_name='gamma', 
                                            param_range=param_range,scoring='accuracy',
                                           cv=3)

    mean_train = train_scores.mean(axis=1)
    mean_test = test_scores.mean(axis=1)
    return (mean_train,mean_test)

answer_six()

(array([0.56646972, 0.93106844, 0.990645  , 1.        , 1.        ,
        1.        ]),
 array([0.56720827, 0.9300837 , 0.98966027, 1.        , 0.99458395,
        0.52240276]))

In [232]:
def answer_seven():
    scores = answer_six()
    s = pd.DataFrame(param_range,mean_test)
    s['mean_train'] = mean_train
    s = s.reset_index()
    s=s.rename({'index':'mean_test',0:'gamma'},axis=1)
    return s['gamma'][0],s['gamma'][5],s['gamma'][3]

answer_seven()

(0.0001, 10.0, 0.1)

In [231]:
param_range

array([1.e-04, 1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01])

(6,)